### ISSUE TITLE
Project Grade Calculation

### ISSUE THREAD

**Issue by ryansdowning** [hcorrada/shiny320grade#1]
I could be wrong, but isn't:

```
project_pct <- reactive({
        max(sapply(3:5, function(i) {
            numerator <- sum(project_scores())
            denominator <- sum(project_totals[-i])
            numerator / denominator
        }))
    })
```

The same as `project_pct <- reactive({ sum(project_scores()) / 275 })`? The `sapply` simply changes the denominator, which is static (not changed by the user). Since `max` is just finding the largest `numerator / denominator`, it will just choose the one with the lowest denominator (which is always 275). I tested this with my grades and it yielded the same results, not sure about other combinations.

Again, I'm not terribly familiar with R syntax, so I could be wrong.

**Comment by hcorrada** [comment]
That's right, I'll leave as is since change does not affect correctness
